# Generated by Django 5.2.4 on 2025-07-11 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('youtube_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
